### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by celyes** [danilopolani/laravel-fusionauth-jwt#1]
I followed the README but got this error: 
 ```sh
Argument 2 passed to DaniloPolani\\FusionAuthJwt\\FusionAuthJwtServiceProvider::DaniloPolani\\FusionAuthJwt\\{closure}() must be an instance of DaniloPolani\\FusionAuthJwt\\FusionAuthJwtUserProvider, null given
```
Any Idea?

**Comment by danilopolani** [comment]
Hey,
I tried to install it on a fresh Laravel 9 instance and everything just worked fine.

Do you have any steps to reproduce it starting from a fresh L9 installation?

**Comment by celyes** [comment]
Thank you for replying @danilopolani. I figured out that the error isn't in the package. It's in the legacy project I'm trying to maintain. Thank you so much again!

**Comment by danilopolani** [comment]
> Thank you for replying @danilopolani. I figured out that the error isn't in the package. It's in the legacy project I'm trying to maintain. Thank you so much again!

Happy to hear it! Have a great weekend 😄
